name: GDSR-D2A2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pytorch=1.8.0
  - torchvision=0.9.0
  - torchaudio=0.8.0
  - cudatoolkit=11.1
  - pip:
    - tqdm==4.66.1
    - scikit-image==0.19.3
    - einops==0.6.1
    - opencv-python-headless==4.8.1.78
    - matplotlib=3.5.3
